[package]
name = "icu"
version = "0.1.0"
edition = "2021"
authors = ["Benign X", "W-Mai"]
homepage = "https://github.com/W-Mai/icu"
description = "Image Converter Utility Library"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icu_lib = {path = "icu_lib"}
clap = { version = "4.4.18", features = ["derive", "suggestions"] }
eframe = { version = "0.26.0", features = ["glow"] }
egui_plot = "0.26.0"

[profile.release]
lto = true
opt-level = 3
