[package]
name = "icu_tool"
version = "0.1.1"
edition = "2021"
authors = ["Benign X", "W-Mai"]
homepage = "https://github.com/W-Mai/icu"
description = "Image Converter Ultra"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "icu"
path = "src/main.rs"

[dependencies]
icu_lib = { version = "0.1.1" }
clap = { version = "4.4.18", features = ["derive", "suggestions"] }
eframe = { version = "0.26.0", features = ["glow"] }
egui_plot = "0.26.0"
log = "0.4.20"
env_logger = "0.11.2"

[patch.crates-io]
icu_lib = { path = "icu_lib" }

[profile.release]
lto = true
opt-level = 3
